seed: 94

save_model_path: ""

trainer:
  _target_: lightning.Trainer
  devices:
    - 0
  precision: "16-mixed"
  max_steps: 50000
  val_check_interval: 1.0
  num_sanity_val_steps: 0
  limit_val_batches: 1
  gradient_clip_val: 1.0
