seed: 15

trainer:
  _target_: lightning.Trainer
  devices:
    - 0
  precision: "16-mixed"
  max_steps: 150000
  val_check_interval: 5000
  num_sanity_val_steps: 0
  limit_val_batches: 1
  gradient_clip_val: 1.0

save_model_path: /root/relik-sapienzanlp/models/${model_name}-${now:%Y-%m-%d-%H-%M-%S}-{val_f1:.2f}
ckpt_path: